Change parameters.cluster.dist to parameters.facts.distribution
projectsyn/component-system-upgrade-controller pull request #7
Opened 2020-09-29 12:14 UTC by megian

See issue #4. Related to projectsyn/commodore#192.

## Checklist

- [x] Keep pull requests small so they can be easily reviewed.
- [x] Update the ./CHANGELOG.md.
- [x] Link this PR to related issues.

2020-09-29 12:33 UTC, corvus-ch requested changes

2020-09-29 12:33 UTC, corvus-ch commented on CHANGELOG.md
> +- Change parameters.cluster.dist to parameters.facts.distribution
```suggestion
- Change parameters.cluster.dist to parameters.facts.distribution ([#7])
```

2020-09-29 12:33 UTC, corvus-ch commented on CHANGELOG.md
>  [Unreleased]: https://github.com/projectsyn/component-system-upgrade-controller/compare/v0.1.0...HEAD
```suggestion
[Unreleased]: https://github.com/projectsyn/component-system-upgrade-controller/compare/2606b0b...HEAD

[#7]: https://github.com/projectsyn/component-system-upgrade-controller/pull/7
```

2020-09-29 12:38 UTC, corvus-ch approved these changes

2020-10-01 12:04 UTC, simu approved these changes

2020-10-01 12:31 UTC, merged